name: Cypress Tests - In Class Project

on:
  push:  # executa em qualquer push (incluindo main)

jobs:
  Cypress-testes-automatizados-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove node_modules comitados
        run: rm -rf ./Cypress-testes-automatizados/node_modules

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: Cypress-testes-automatizados/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('Cypress-testes-automatizados/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('Cypress-testes-automatizados/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm install
        working-directory: ./Cypress-testes-automatizados

      - name: Install Cypress binary (force)
        run: npx cypress install --force
        working-directory: ./Cypress-testes-automatizados

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./Cypress-testes-automatizados
